#############################################################################
# Makefile for building: seaBattle.app/Contents/MacOS/seaBattle
# Generated by qmake (3.1) (Qt 5.8.0)
# Project:  seaBattle.pro
# Template: app
# Command: /Applications/Qt5.8.0/5.8/clang_64/bin/qmake -o Makefile seaBattle.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.9 $(EXPORT_QMAKE_XARCH_CFLAGS) -g -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.9 $(EXPORT_QMAKE_XARCH_CFLAGS) -g -std=gnu++11 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers -I/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers -I/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I/Applications/Qt5.8.0/5.8/clang_64/mkspecs/macx-clang -F/Applications/Qt5.8.0/5.8/clang_64/lib
QMAKE         = /Applications/Qt5.8.0/5.8/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = seaBattle1.0.0
DISTDIR = /Users/anton/Documents/seaBattle/.tmp/seaBattle1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -stdlib=libc++ -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.9 $(EXPORT_QMAKE_XARCH_LFLAGS) -Wl,-rpath,/Applications/Qt5.8.0/5.8/clang_64/lib
LIBS          = $(SUBLIBS) -F/Applications/Qt5.8.0/5.8/clang_64/lib -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		mypoint.cpp \
		client.cpp \
		server.cpp \
		servclient.cpp qrc_res.cpp \
		moc_mainwindow.cpp \
		moc_mypoint.cpp \
		moc_client.cpp \
		moc_server.cpp \
		moc_servclient.cpp
OBJECTS       = main.o \
		mainwindow.o \
		mypoint.o \
		client.o \
		server.o \
		servclient.o \
		qrc_res.o \
		moc_mainwindow.o \
		moc_mypoint.o \
		moc_client.o \
		moc_server.o \
		moc_servclient.o
DIST          = /Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/spec_pre.prf \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/qdevice.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/device_config.prf \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/common/unix.conf \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/common/mac.conf \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/common/macx.conf \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/common/sanitize.conf \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/common/gcc-base.conf \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/common/clang.conf \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/common/clang-mac.conf \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/qconfig.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_charts.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_location.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webview.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/qt_functions.prf \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/qt_config.prf \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/macx-clang/qmake.conf \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/spec_post.prf \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/exclusive_builds.prf \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/mac/sdk.prf \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/toolchain.prf \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/mac/toolchain.prf \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/default_pre.prf \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/mac/default_pre.prf \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/resolve_config.prf \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/default_post.prf \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/mac/default_post.prf \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/mac/objective_c.prf \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/qml_debug.prf \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/warn_on.prf \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/qt.prf \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/resources.prf \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/moc.prf \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/unix/opengl.prf \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/uic.prf \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/unix/thread.prf \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/qmake_use.prf \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/file_copies.prf \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/mac/rez.prf \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/testcase_targets.prf \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/exceptions.prf \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/yacc.prf \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/lex.prf \
		seaBattle.pro mainwindow.h \
		mypoint.h \
		client.h \
		server.h \
		servclient.h main.cpp \
		mainwindow.cpp \
		mypoint.cpp \
		client.cpp \
		server.cpp \
		servclient.cpp
QMAKE_TARGET  = seaBattle
DESTDIR       = 
TARGET        = seaBattle.app/Contents/MacOS/seaBattle


first: all
####### Build rules

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	@test -d seaBattle.app/Contents/MacOS/ || mkdir -p seaBattle.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: seaBattle.pro /Applications/Qt5.8.0/5.8/clang_64/mkspecs/macx-clang/qmake.conf /Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/spec_pre.prf \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/qdevice.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/device_config.prf \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/common/unix.conf \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/common/mac.conf \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/common/macx.conf \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/common/sanitize.conf \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/common/gcc-base.conf \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/common/clang.conf \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/common/clang-mac.conf \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/qconfig.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_charts.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_location.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webview.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/qt_functions.prf \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/qt_config.prf \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/macx-clang/qmake.conf \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/spec_post.prf \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/exclusive_builds.prf \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/mac/sdk.prf \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/toolchain.prf \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/mac/toolchain.prf \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/default_pre.prf \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/mac/default_pre.prf \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/resolve_config.prf \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/default_post.prf \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/mac/default_post.prf \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/mac/objective_c.prf \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/qml_debug.prf \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/warn_on.prf \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/qt.prf \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/resources.prf \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/moc.prf \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/unix/opengl.prf \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/uic.prf \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/unix/thread.prf \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/qmake_use.prf \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/file_copies.prf \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/mac/rez.prf \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/testcase_targets.prf \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/exceptions.prf \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/yacc.prf \
		/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/lex.prf \
		seaBattle.pro \
		res.qrc \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/QtGui.prl \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile seaBattle.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/spec_pre.prf:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/qdevice.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/device_config.prf:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/common/unix.conf:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/common/mac.conf:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/common/macx.conf:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/common/sanitize.conf:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/common/gcc-base.conf:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/common/gcc-base-mac.conf:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/common/clang.conf:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/common/clang-mac.conf:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/qconfig.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3drender.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_charts.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_charts_private.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_core.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_core_private.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_dbus.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_designer.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_gui.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_help.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_help_private.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_location.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_location_private.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_macextras.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_network.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_network_private.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_networkauth.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_nfc.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_opengl.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_positioning.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_purchasing.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qml.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quick.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_script.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_script_private.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_scxml.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_sensors.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_serialport.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_sql.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_svg.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_testlib.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_uitools.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webengine.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_websockets.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webview.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_widgets.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_xml.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/qt_functions.prf:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/qt_config.prf:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/macx-clang/qmake.conf:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/spec_post.prf:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/exclusive_builds.prf:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/mac/sdk.prf:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/toolchain.prf:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/mac/toolchain.prf:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/default_pre.prf:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/mac/default_pre.prf:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/resolve_config.prf:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/default_post.prf:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/mac/default_post.prf:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/mac/objective_c.prf:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/qml_debug.prf:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/warn_on.prf:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/qt.prf:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/resources.prf:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/moc.prf:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/unix/opengl.prf:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/uic.prf:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/unix/thread.prf:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/qmake_use.prf:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/file_copies.prf:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/mac/rez.prf:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/mac/asset_catalogs.prf:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/testcase_targets.prf:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/exceptions.prf:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/yacc.prf:
/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/lex.prf:
seaBattle.pro:
res.qrc:
/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/QtGui.prl:
/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile seaBattle.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug

qmake_all: FORCE

seaBattle.app/Contents/PkgInfo: 
	@test -d seaBattle.app/Contents || mkdir -p seaBattle.app/Contents
	@$(DEL_FILE) seaBattle.app/Contents/PkgInfo
	@echo "APPL????" > seaBattle.app/Contents/PkgInfo
seaBattle.app/Contents/Resources/empty.lproj: 
	@test -d seaBattle.app/Contents/Resources || mkdir -p seaBattle.app/Contents/Resources
	@touch seaBattle.app/Contents/Resources/empty.lproj
	
seaBattle.app/Contents/Info.plist: 
	@test -d seaBattle.app/Contents || mkdir -p seaBattle.app/Contents
	@$(DEL_FILE) seaBattle.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,5091.seaBattle,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,seaBattle,g" -e "s,@LIBRARY@,seaBattle,g" -e "s,@TYPEINFO@,????,g" /Applications/Qt5.8.0/5.8/clang_64/mkspecs/macx-clang/Info.plist.app >seaBattle.app/Contents/Info.plist

all: Makefile \
		seaBattle.app/Contents/PkgInfo \
		seaBattle.app/Contents/Resources/empty.lproj \
		seaBattle.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents res.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h mypoint.h client.h server.h servclient.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp mypoint.cpp client.cpp server.cpp servclient.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r seaBattle.app
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_res.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_res.cpp
qrc_res.cpp: res.qrc \
		/Applications/Qt5.8.0/5.8/clang_64/bin/rcc \
		Dot.png \
		StartBack.png \
		sh_1.png \
		cell.png \
		FieldBack.png \
		Kill.png \
		PlacingBack.png \
		sh_4.png \
		sh_3.png \
		Half.png \
		sh_2.png
	/Applications/Qt5.8.0/5.8/clang_64/bin/rcc -name res res.qrc -o qrc_res.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.9 $(EXPORT_QMAKE_XARCH_CFLAGS) -g -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h /Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_mypoint.cpp moc_client.cpp moc_server.cpp moc_servclient.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_mypoint.cpp moc_client.cpp moc_server.cpp moc_servclient.cpp
moc_mainwindow.cpp: /Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QObject \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qobject.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QString \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qstring.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QVector \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qvector.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QDebug \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		mypoint.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/QGraphicsItem \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/QPainter \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		client.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QTimer \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		mainwindow.h \
		server.h \
		servclient.h \
		mainwindow.h \
		moc_predefs.h \
		/Applications/Qt5.8.0/5.8/clang_64/bin/moc
	/Applications/Qt5.8.0/5.8/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Applications/Qt5.8.0/5.8/clang_64/mkspecs/macx-clang -I/Users/anton/Documents/seaBattle -I/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers -I/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers -I/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.1.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -F/Applications/Qt5.8.0/5.8/clang_64/lib mainwindow.h -o moc_mainwindow.cpp

moc_mypoint.cpp: /Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QObject \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qobject.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/QGraphicsItem \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/QPainter \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		mypoint.h \
		moc_predefs.h \
		/Applications/Qt5.8.0/5.8/clang_64/bin/moc
	/Applications/Qt5.8.0/5.8/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Applications/Qt5.8.0/5.8/clang_64/mkspecs/macx-clang -I/Users/anton/Documents/seaBattle -I/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers -I/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers -I/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.1.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -F/Applications/Qt5.8.0/5.8/clang_64/lib mypoint.h -o moc_mypoint.cpp

moc_client.cpp: /Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QObject \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qobject.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QTimer \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		mypoint.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/QGraphicsItem \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/QPainter \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		mainwindow.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QString \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qstring.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QVector \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qvector.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QDebug \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		client.h \
		server.h \
		servclient.h \
		client.h \
		moc_predefs.h \
		/Applications/Qt5.8.0/5.8/clang_64/bin/moc
	/Applications/Qt5.8.0/5.8/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Applications/Qt5.8.0/5.8/clang_64/mkspecs/macx-clang -I/Users/anton/Documents/seaBattle -I/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers -I/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers -I/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.1.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -F/Applications/Qt5.8.0/5.8/clang_64/lib client.h -o moc_client.cpp

moc_server.cpp: /Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QObject \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qobject.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QTimer \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QDebug \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		servclient.h \
		client.h \
		mypoint.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/QGraphicsItem \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/QPainter \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		mainwindow.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QString \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qstring.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QVector \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qvector.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		server.h \
		server.h \
		moc_predefs.h \
		/Applications/Qt5.8.0/5.8/clang_64/bin/moc
	/Applications/Qt5.8.0/5.8/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Applications/Qt5.8.0/5.8/clang_64/mkspecs/macx-clang -I/Users/anton/Documents/seaBattle -I/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers -I/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers -I/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.1.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -F/Applications/Qt5.8.0/5.8/clang_64/lib server.h -o moc_server.cpp

moc_servclient.cpp: /Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QObject \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qobject.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QTimer \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QDebug \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		client.h \
		mypoint.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/QGraphicsItem \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/QPainter \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		mainwindow.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QString \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qstring.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QVector \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qvector.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		server.h \
		servclient.h \
		servclient.h \
		moc_predefs.h \
		/Applications/Qt5.8.0/5.8/clang_64/bin/moc
	/Applications/Qt5.8.0/5.8/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Applications/Qt5.8.0/5.8/clang_64/mkspecs/macx-clang -I/Users/anton/Documents/seaBattle -I/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers -I/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers -I/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.1.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -F/Applications/Qt5.8.0/5.8/clang_64/lib servclient.h -o moc_servclient.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		/Applications/Qt5.8.0/5.8/clang_64/bin/uic
	/Applications/Qt5.8.0/5.8/clang_64/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QObject \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qobject.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QString \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qstring.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QVector \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qvector.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QDebug \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		mypoint.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/QGraphicsItem \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/QPainter \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		client.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QTimer \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		server.h \
		servclient.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QObject \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qobject.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QString \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qstring.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QVector \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qvector.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QDebug \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		mypoint.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/QGraphicsItem \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/QPainter \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		client.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QTimer \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		server.h \
		servclient.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

mypoint.o: mypoint.cpp mypoint.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QObject \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qobject.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/QGraphicsItem \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/QPainter \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		mainwindow.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QString \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qstring.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QVector \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qvector.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QDebug \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		client.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QTimer \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		server.h \
		servclient.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mypoint.o mypoint.cpp

client.o: client.cpp client.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QObject \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qobject.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QTimer \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		mypoint.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/QGraphicsItem \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/QPainter \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		mainwindow.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QString \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qstring.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QVector \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qvector.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QDebug \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		server.h \
		servclient.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o client.o client.cpp

server.o: server.cpp server.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QObject \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qobject.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QTimer \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QDebug \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		servclient.h \
		client.h \
		mypoint.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/QGraphicsItem \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/QPainter \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		mainwindow.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QString \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qstring.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QVector \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qvector.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o server.o server.cpp

servclient.o: servclient.cpp servclient.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QObject \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qobject.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QTimer \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QDebug \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		client.h \
		mypoint.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/QGraphicsItem \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/QPainter \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		mainwindow.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QString \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qstring.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QVector \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qvector.h \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		server.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o servclient.o servclient.cpp

qrc_res.o: qrc_res.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_res.o qrc_res.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_mypoint.o: moc_mypoint.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mypoint.o moc_mypoint.cpp

moc_client.o: moc_client.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_client.o moc_client.cpp

moc_server.o: moc_server.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_server.o moc_server.cpp

moc_servclient.o: moc_servclient.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_servclient.o moc_servclient.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

